# a selection of languages supported by the translator
LANGUAGES = [
    ("auto", "Auto"),
    ("en", "English"),
    ("de", "German"),
    ("ru", "Russian"),
    ("uk", "Ukrainian"),
    ("pl", "Polish"),
    ("fr", "French"),
    ("es", "Spanish"),
    ("pt", "Portuguese"),
    ("tr", "Turkish"),
    ("sv", "Swedish"),
    ("zh", "Chinese"),
    ("ja", "Japanese"),
    ("ko", "Korean"),
    ("ar", "Arabic"),
]

# display names for all languages that might be detected
_LID176_LANG_CODE_TO_NAME = {
    'af': 'Afrikaans',
    'als': 'Tosk Albanian',
    'am': 'Amharic',
    'an': 'Aragonese',
    'ar': 'Arabic',
    'arz': 'Egyptian Arabic',
    'as': 'Assamese',
    'ast': 'Asturian',
    'av': 'Avaric',
    'az': 'Azerbaijani',
    'azb': 'South Azerbaijani',
    'ba': 'Bashkir',
    'bar': 'Bavarian',
    'bcl': 'Central Bikol',
    'be': 'Belarusian',
    'bg': 'Bulgarian',
    'bh': 'Bihari languages',
    'bn': 'Bengali',
    'bo': 'Tibetan',
    'bpy': 'Bishnupriya',
    'br': 'Breton',
    'bs': 'Bosnian',
    'bxr': 'Russia Buriat',
    'ca': 'Catalan',
    'cbk': 'Chavacano',
    'ce': 'Chechen',
    'ceb': 'Cebuano',
    'ckb': 'Central Kurdish',
    'co': 'Corsican',
    'cs': 'Czech',
    'cv': 'Chuvash',
    'cy': 'Welsh',
    'da': 'Danish',
    'de': 'German',
    'diq': 'Dimli',
    'dsb': 'Lower Sorbian',
    'dty': 'Dotyali',
    'dv': 'Dhivehi',
    'el': 'Greek',
    'eml': 'Emiliano-Romagnolo',
    'en': 'English',
    'eo': 'Esperanto',
    'es': 'Spanish',
    'et': 'Estonian',
    'eu': 'Basque',
    'fa': 'Persian',
    'fi': 'Finnish',
    'fr': 'French',
    'frr': 'Northern Frisian',
    'fy': 'Western Frisian',
    'ga': 'Irish',
    'gd': 'Scottish Gaelic',
    'gl': 'Galician',
    'gn': 'Guarani',
    'gom': 'Goan Konkani',
    'gu': 'Gujarati',
    'gv': 'Manx',
    'he': 'Hebrew',
    'hi': 'Hindi',
    'hif': 'Fiji Hindi',
    'hr': 'Croatian',
    'hsb': 'Upper Sorbian',
    'ht': 'Haitian',
    'hu': 'Hungarian',
    'hy': 'Armenian',
    'ia': 'Interlingua',
    'id': 'Indonesian',
    'ie': 'Interlingue',
    'ilo': 'Iloko',
    'io': 'Ido',
    'is': 'Icelandic',
    'it': 'Italian',
    'ja': 'Japanese',
    'jbo': 'Lojban',
    'jv': 'Javanese',
    'ka': 'Georgian',
    'kk': 'Kazakh',
    'km': 'Central Khmer',
    'kn': 'Kannada',
    'ko': 'Korean',
    'krc': 'Karachay-Balkar',
    'ku': 'Kurdish',
    'kv': 'Komi',
    'kw': 'Cornish',
    'ky': 'Kirghiz',
    'la': 'Latin',
    'lb': 'Luxembourgish',
    'lez': 'Lezghian',
    'li': 'Limburgan',
    'lmo': 'Lombard',
    'lo': 'Lao',
    'lrc': 'Northern Luri',
    'lt': 'Lithuanian',
    'lv': 'Latvian',
    'mai': 'Maithili',
    'mg': 'Malagasy',
    'mhr': 'Eastern Mari',
    'min': 'Minangkabau',
    'mk': 'Macedonian',
    'ml': 'Malayalam',
    'mn': 'Mongolian',
    'mr': 'Marathi',
    'mrj': 'Western Mari',
    'ms': 'Malay',
    'mt': 'Maltese',
    'mwl': 'Mirandese',
    'my': 'Burmese',
    'myv': 'Erzya',
    'mzn': 'Mazanderani',
    'nah': 'Nahuatl languages',
    'nap': 'Neapolitan',
    'nds': 'Low German',
    'ne': 'Nepali',
    'new': 'Newari',
    'nl': 'Dutch',
    'nn': 'Norwegian Nynorsk',
    'no': 'Norwegian',
    'oc': 'Occitan',
    'or': 'Oriya',
    'os': 'Ossetian',
    'pa': 'Panjabi',
    'pam': 'Pampanga',
    'pfl': 'Pfaelzisch',
    'pl': 'Polish',
    'pms': 'Piemontese',
    'pnb': 'Western Panjabi',
    'ps': 'Pushto',
    'pt': 'Portuguese',
    'qu': 'Quechua',
    'rm': 'Romansh',
    'ro': 'Romanian',
    'ru': 'Russian',
    'rue': 'Rusyn',
    'sa': 'Sanskrit',
    'sah': 'Yakut',
    'sc': 'Sardinian',
    'scn': 'Sicilian',
    'sco': 'Scots',
    'sd': 'Sindhi',
    'sh': 'Serbo-Croatian',
    'si': 'Sinhala',
    'sk': 'Slovak',
    'sl': 'Slovenian',
    'so': 'Somali',
    'sq': 'Albanian',
    'sr': 'Serbian',
    'su': 'Sundanese',
    'sv': 'Swedish',
    'sw': 'Swahili',
    'ta': 'Tamil',
    'te': 'Telugu',
    'tg': 'Tajik',
    'th': 'Thai',
    'tk': 'Turkmen',
    'tl': 'Tagalog',
    'tr': 'Turkish',
    'tt': 'Tatar',
    'tyv': 'Tuvinian',
    'ug': 'Uighur',
    'uk': 'Ukrainian',
    'ur': 'Urdu',
    'uz': 'Uzbek',
    'vec': 'Venetian',
    'vep': 'Veps',
    'vi': 'Vietnamese',
    'vls': 'Vlaams',
    'vo': 'Volapük',
    'wa': 'Walloon',
    'war': 'Waray',
    'wuu': 'Wu Chinese',
    'xal': 'Kalmyk',
    'xmf': 'Mingrelian',
    'yi': 'Yiddish',
    'yo': 'Yoruba',
    'yue': 'Yue Chinese',
    'zh': 'Chinese',
}

_LANG_CODE_TO_NAME = dict(LANGUAGES)
_LANG_NAME_TO_CODE = {name.strip().lower(): code for code, name in LANGUAGES}

def get_supported_language_names():
    return [name for _, name in LANGUAGES[1:]]

def language_code_to_name(code: str):
    return _LANG_CODE_TO_NAME.get(code, "Unknown")

def language_name_to_code(name: str):
    name = name.strip().lower()
    return _LANG_NAME_TO_CODE.get(name, None)

def lid176_language_code_to_name(code: str):
    return _LID176_LANG_CODE_TO_NAME.get(code, "Unknown")
